version: '3'
services:
        web:
                build: /home/ranigp86/war-test
                ports:
                  - "9990:8080"
        db:
                image: mysql
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=user
                        - MYSQL_PASSWORD=password
                        - MYSQL_DATABASE=demodb
